HTML:
  beautifiers:
    - Pretty Diff
    - JS-Beautify
  indent_size: 2
CSS:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
    - CSScomb
SCSS:
  beautifiers:
    - Prettier
    - Pretty Diff
    - CSScomb
Sass:
  beautifiers:
    - CSScomb
JavaScript:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
    - ESLint
Python:
  beautifiers:
    - Black
    - YAPF
