version: '3.8'

services:
  mysql:
    build:
      context: ./docker/mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    image: business-reviews_mysql
    container_name: ${DOCKER_COMPOSE_PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - "mysql_data:/var/lib/mysql"
    # networks:
    #   - business-reviews_mysql_network
    restart: always

volumes:
  mysql_data:
    driver: local
